import "./globals.css";
import Nav from "./components/Nav";
import { getServerSession } from "next-auth/next";
import { options } from "@/pages/api/auth/[...nextauth]";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //Fetch the user
  const session = await getServerSession(options);
  console.log(session);
  return (
    <html lang="en">
      <body>
        <div className="container">
          <Nav user={session?.user} expires={session?.expires as string} />
          {children}
        </div>
      </body>
    </html>
  );
}
